name: Mobile CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  web-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      
    - name: Build web app
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: dist/
        retention-days: 7

  capacitor-sync:
    runs-on: ubuntu-latest
    needs: web-build
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: dist/
        
    - name: Sync Capacitor
      run: npx cap sync
      
    - name: Upload iOS project
      uses: actions/upload-artifact@v4
      with:
        name: ios-project
        path: ios/
        retention-days: 7
        
    - name: Upload Android project
      uses: actions/upload-artifact@v4
      with:
        name: android-project
        path: android/
        retention-days: 7

  # Note: Actual iOS/Android builds require platform-specific runners
  # and signing certificates which should be set up separately
  
  security-scan:
    runs-on: ubuntu-latest
    needs: web-build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      continue-on-error: true
      
    - name: Check for known vulnerabilities
      run: npx audit-ci --config .audit-ci.json
      continue-on-error: true